In [1118]:
import pandas as pd
import numpy as np
import ast

In [1119]:
movies = pd.read_csv(r"C:\Users\Prachi Singh\OneDrive\Desktop\Projects\imdb_movie_dataset.csv")
movies.head(3)

Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1     2               Prometheus  Adventure,Mystery,Sci-Fi   
2     3                    Split           Horror,Thriller   

                                         Description            Director  \
0  A group of intergalactic criminals are forced ...          James Gunn   
1  Following clues to the origin of mankind, a te...        Ridley Scott   
2  Three girls are kidnapped by a man with a diag...  M. Night Shyamalan   

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121   
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124   
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117   

   Rating   Votes  Revenue (Millions)  Metascore  
0     8.1  757074              333.13       76.0  
1     7.0  485820              126.46       65.0  
2     7.3  157606              138.12       62.0

In [1120]:
movies = movies[['Rank', 'Title','Genre', 'Description','Director','Actors']]

In [1121]:
movies.head(1)

Rank                    Title                    Genre  \
0     1  Guardians of the Galaxy  Action,Adventure,Sci-Fi   

                                         Description    Director  \
0  A group of intergalactic criminals are forced ...  James Gunn   

                                              Actors  
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...

In [1122]:
movies.isnull().sum()

Rank           0
Title          0
Genre          0
Description    0
Director       0
Actors         0
dtype: int64

In [1123]:
movies.duplicated().sum()

np.int64(0)

In [1124]:
movies['Title']=movies['Title'].apply(lambda x:x.replace(" ",""))
movies['Genre']=movies['Genre'].apply(lambda x:x.replace(" ",""))
movies['Description']=movies['Description'].apply(lambda x:x.replace(" ",""))
movies['Director']=movies['Director'].apply(lambda x:x.replace(" ",""))
movies['Actors']=movies['Actors'].apply(lambda x:x.replace(" ",""))




In [1125]:
movies['Tags'] = movies['Title']+movies['Genre']+movies['Description']+movies['Director']+movies['Actors']
movies.head()

Rank                 Title                     Genre  \
0     1  GuardiansoftheGalaxy   Action,Adventure,Sci-Fi   
1     2            Prometheus  Adventure,Mystery,Sci-Fi   
2     3                 Split           Horror,Thriller   
3     4                  Sing   Animation,Comedy,Family   
4     5          SuicideSquad  Action,Adventure,Fantasy   

                                         Description             Director  \
0  Agroupofintergalacticcriminalsareforcedtoworkt...            JamesGunn   
1  Followingcluestotheoriginofmankind,ateamfindsa...          RidleyScott   
2  Threegirlsarekidnappedbyamanwithadiagnosed23di...     M.NightShyamalan   
3  Inacityofhumanoidanimals,ahustlingtheaterimpre...  ChristopheLourdelet   
4  Asecretgovernmentagencyrecruitssomeofthemostda...            DavidAyer   

                                              Actors  \
0      ChrisPratt,VinDiesel,BradleyCooper,ZoeSaldana   
1  NoomiRapace,LoganMarshall-Green,MichaelFassben...   
2  JamesMcAvoy,AnyaTaylor-Joy,HaleyLuRichardson,J...   
3  MatthewMcConaughey,ReeseWitherspoon,SethMacFar...   
4        WillSmith,JaredLeto,MargotRobbie,ViolaDavis   

                                                Tags  
0  GuardiansoftheGalaxyAction,Adventure,Sci-FiAgr...  
1  PrometheusAdventure,Mystery,Sci-FiFollowingclu...  
2  SplitHorror,ThrillerThreegirlsarekidnappedbyam...  
3  SingAnimation,Comedy,FamilyInacityofhumanoidan...  
4  SuicideSquadAction,Adventure,FantasyAsecretgov...

In [1126]:
new_data = movies[['Rank','Title','Tags']]
new_data.head()    

Rank                 Title  \
0     1  GuardiansoftheGalaxy   
1     2            Prometheus   
2     3                 Split   
3     4                  Sing   
4     5          SuicideSquad   

                                                Tags  
0  GuardiansoftheGalaxyAction,Adventure,Sci-FiAgr...  
1  PrometheusAdventure,Mystery,Sci-FiFollowingclu...  
2  SplitHorror,ThrillerThreegirlsarekidnappedbyam...  
3  SingAnimation,Comedy,FamilyInacityofhumanoidan...  
4  SuicideSquadAction,Adventure,FantasyAsecretgov...

In [1127]:
new_data['Tags'] = new_data['Tags'].apply(lambda x:x.lower())
new_data['Tags']

C:\Users\Prachi Singh\AppData\Local\Temp\ipykernel_1220\3611343782.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['Tags'] = new_data['Tags'].apply(lambda x:x.lower())


0      guardiansofthegalaxyaction,adventure,sci-fiagr...
1      prometheusadventure,mystery,sci-fifollowingclu...
2      splithorror,thrillerthreegirlsarekidnappedbyam...
3      singanimation,comedy,familyinacityofhumanoidan...
4      suicidesquadaction,adventure,fantasyasecretgov...
                             ...                        
995    secretintheireyescrime,drama,mysteryatight-kni...
996    hostel:partiihorrorthreeamericancollegestudent...
997    stepup2:thestreetsdrama,music,romanceromantics...
998    searchpartyadventure,comedyapairoffriendsembar...
999    ninelivescomedy,family,fantasyastuffybusinessm...
Name: Tags, Length: 1000, dtype: object

In [1128]:
from sklearn.feature_extraction.text import CountVectorizer



In [1129]:
cv = CountVectorizer(max_features = 7000,stop_words ='english')


In [1130]:
vectors = cv.fit_transform(new_data['Tags']).toarray()
print(vectors)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [1131]:
cv.get_feature_names_out()

array(['000savingsaccounttocharityandhitchhikestoalaskatoliveinthewilderness',
       '000slavesonamonumentaljourneyofescapefromegyptanditsterrifyingcycleofdeadlyplagues',
       '007musttrackdownanddestroythethreat', ..., 'zootopiaanimation',
       'zoëbell', 'zoëkravitz'], shape=(7000,), dtype=object)

In [1132]:
from sklearn.metrics.pairwise import cosine_similarity

In [1133]:
similarity = cosine_similarity(vectors)
similarity

array([[1.        , 0.10660036, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.10660036, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]], shape=(1000, 1000))

In [1134]:
sorted(list(enumerate(similarity[0]))
                       ,reverse = True,
                       key=lambda x: x[1])[1:6]

[(48, np.float64(0.35355339059327373)),
 (362, np.float64(0.3198010745334156)),
 (87, np.float64(0.26726124191242434)),
 (472, np.float64(0.26726124191242434)),
 (227, np.float64(0.24999999999999994))]

In [1135]:
def recommend (movie_name):
  
  movie = movie_name.replace(" ", "")
  matches = new_data[new_data['Title'] == movie]
  
  if matches.empty:
        print("Movie not found in dataset")
        return

  movie_index = matches.index[0]
    
  distances =similarity[movie_index]
  movie_list = sorted(list(enumerate(distances))
                        ,reverse = True,
                       key=lambda x: x[1])[1:5]
  for i in movie_list:
       print(new_data.iloc[i[0]].Title)
  

In [1136]:
recommend('Guardians of the Galaxy')

StarTrekBeyond
StarTrekIntoDarkness
Avatar
2012


In [1137]:
import pickle

In [1138]:
pickle.dump(
    new_data.to_dict(),
    open('movies_dict.pkl', 'wb')
)


In [1139]:
pickle.dump(similarity,open('similarity.pkl','wb'))